script: |
  export NVM_DIR=~/.nvm
  source ~/.nvm/nvm.sh                

name: Node.js CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ..
            ls
            npm -v
            # rm -r demo-ci-cd
            # git clone https://github.com/VictorTrumpel/demo-ci-cd
            # cd demo-ci-cd
            # npm i
            # npm run build
            # rm -r ../../var/www/build
            # mv build ../../var/www
