name: Deploy

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: "Ветка, которую нужно развернуть"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ..
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh    
            { if [ -d demo-ci-cd ]; then rm -r demo-ci-cd; fi; }
            git clone https://github.com/VictorTrumpel/demo-ci-cd -b ${{ inputs.branchName }}
            cd demo-ci-cd
            npm i
            npm run build
            rm -r ../../var/www/build
            mv build ../../var/www
