name: Deploy React App
on: 
  push:
    branches:
      - main
    paths-ignore: 
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run test
      - name: Lint application
        run: npm run lint
      - name: Deploy
        run: echo Deploying ...
